import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import MyMapComponent from "../components/MyMapComponent";
import Map from "@/components/Map";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const locations = [
    {
      name: "مدرسة 1",
      coordinates: { lat: 25.123, lng: 51.456 },
      category: "مدرسة",
    },
    {
      name: "مستشفى 1",
      coordinates: { lat: 25.234, lng: 51.567 },
      category: "مستشفى",
    },
    // ... المزيد من المواقع
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map locations={locations} />
      </main>
    </>
  );
}
